### ISSUE TITLE
TypeError: _print_commands_panel() missing 1 required keyword-only argument:  'cmd_len'

### ISSUE THREAD

**Issue by kylebayler** [torchbox/heroku-audit#5]
While updating https://github.com/torchbox/homebrew-tap/pull/7/files to support python3.12+, I noticed this error:

```
TypeError: _print_commands_panel() missing 1 required keyword-only argument: 
'cmd_len'
```

When running: `heroku-audit --list`

I'm not sure why this is happening, as it looks like we're passing a `cmd_len` kwarg: https://github.com/torchbox/heroku-audit/blob/main/heroku_audit/cli/__init__.py#L53

Should we pin `typer` to a specific version to avoid breaking changes when new versions of typer are released?

**Comment by RealOrangeOne** [comment]
This should be fixed in https://github.com/torchbox/heroku-audit/commit/ba4d3c52440af26a3613827f6eb40cc6fcc87304, but yes probably pinning dependencies might be the way forward here.

**Comment by kbayliss** [comment]
@RealOrangeOne Oh ffs :). I forgot to check the changes in `main` were actually released 🤦 . Thanks!

**Comment by RealOrangeOne** [comment]
Now! :partying_face: https://github.com/torchbox/heroku-audit/releases/tag/0.0.3
